AllCops:
  Exclude:
    - login/runner.rb

Style/Documentation:
  Enabled: false

GlobalVars:
  AllowedVariables:
    - $running

Layout/ClassStructure:
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Max: 150
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  Max: 7