AllCops:
  Exclude:
    - login/runner.rb

Style/Documentation:
  Enabled: false

GlobalVars:
  AllowedVariables:
    - $running

Layout/ClassStructure:
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/LineLenght:
  Max: 120